### PR TITLE
feat: Prepare for Vue 3

### PR DESCRIPTION
**Pull request by susnux**

### CODE REVIEW

**Comment by raimund-schluessler** [comment]
@susnux I rebased and added 10dfa94f6c84c145cf2e10f3c6420b9cd042a3ee to fix an issue occurring in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4599.

**Comment by raimund-schluessler** [comment]
@susnux I currently see this error when using this config now:
```
[commonjs--resolver] Missing "./shims/global" specifier in "vite-plugin-node-polyfills" package
error during build:
Error: Missing "./shims/global" specifier in "vite-plugin-node-polyfills" package
```
Do you thin this is an upstream issue, or do I do something wrong here? I reported it upstream already, see https://github.com/davidmyersdev/vite-plugin-node-polyfills/issues/69, I just wanted to make sure the problem is with the dependency and not with us before continuing upstream.

**Comment by raimund-schluessler** [comment]
> @susnux I currently see this error when using this config now:
> 
> ```
> [commonjs--resolver] Missing "./shims/global" specifier in "vite-plugin-node-polyfills" package
> error during build:
> Error: Missing "./shims/global" specifier in "vite-plugin-node-polyfills" package
> ```
> 
> Do you think this is an upstream issue, or do I do something wrong here? I reported it upstream already, see [davidmyersdev/vite-plugin-node-polyfills#69](https://github.com/davidmyersdev/vite-plugin-node-polyfills/issues/69), I just wanted to make sure the problem is with the dependency and not with us before continuing upstream.

I found the problem. `nextcloud/vue@next` had a dependency against `vite-plugin-node-polyfills@0.15.0` that conflicted with `vite-plugin-node-polyfills@0.19.0` from `nextcloud/vite-config@vue3`. I send a PR against `nextcloud/vue@next` that fixes the issue.

**Review by ShGKme — APPROVED** [review]
🚀

**Pull request merged**
